### ISSUE TITLE
Legend not refreshing

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#222]
The legend (i - button) does not refresh when tagpacks are loaded.

Reproduce:
1.) start with some arbitrary address (e.g., 0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740)
2.) load tagpack with some sample tags and start traversing graph
--> categories listed in tagpack do not show up

![image](https://user-images.githubusercontent.com/366981/133967560-d98b9807-c270-480f-94a1-66564f648968.png)

Example TagPack:

````
title: Example ETH TagPack
creator: Someone
source: null
tagpack_uri: null
currency: ETH
abuse: null
tags:
  - label: Coinbase
    lastmod: 2021-09-20 08:54:19
    category: exchange
    address: "0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740"
  - label: Furucombo
    lastmod: 2021-09-20 08:57:23
    category: service
    address: "0xefa99fa2703430a38d095a29f6dc32dd9fdc5a01"
  - label: OpenSea
    lastmod: 2021-09-20 08:58:55
    category: market
    address: "0x7be8076f4ea4a4ad08075c2508e481d6c946d12b"
  - label: Compound
    lastmod: 2021-09-20 08:58:55
    category: service
    address: "0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b"
  - label: USDC Token
    lastmod: 2021-09-20 08:58:55
    category: service
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  - label: Compound Token
    lastmod: 2021-09-20 08:58:55
    category: service
    address: "0x39aa39c021dfbae8fac545936693ac917d5e7563"

````
